sonar.projectKey=fit-hub-frontend
sonar.organization=tewaripiyush43
sonar.projectName=FitHub Frontend

sonar.sources=src

sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.exclusions=node_modules/**,build/**,coverage/**,public/**

sonar.sourceEncoding=UTF-8